
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('relationships').del()
    .then(function () {
      // Inserts seed entries
      return knex('relationships').insert([
        {id_one: 1, id_two: 2, count: 1},
        {id_one: 1, id_two: 3, count: 2},
        {id_one: 1, id_two: 4, count: 3},
        {id_one: 1, id_two: 5, count: 0},
        {id_one: 1, id_two: 6, count: 0},
        {id_one: 1, id_two: 7, count: 1},
        {id_one: 1, id_two: 8, count: 0},
        {id_one: 1, id_two: 9, count: 1},
        {id_one: 1, id_two: 10, count: 0},
        {id_one: 1, id_two: 11, count: 1},
        {id_one: 1, id_two: 12, count: 2},
        {id_one: 1, id_two: 13,count: 1},
        {id_one: 1, id_two: 14, count: 2},
        {id_one: 1, id_two: 15, count: 0},
        {id_one: 2, id_two: 3, count: 2},
        {id_one: 2, id_two: 4, count: 2},
        {id_one: 2, id_two: 5, count: 0},
        {id_one: 2, id_two: 6, count: 0},
        {id_one: 2, id_two: 7, count: 1},
        {id_one: 2, id_two: 8, count: 0},
        {id_one: 2, id_two: 9, count: 0},
        {id_one: 2, id_two: 10, count: 2},
        {id_one: 2, id_two: 11, count: 0},
        {id_one: 2, id_two: 12, count: 2},
        {id_one: 2, id_two: 13, count: 1},
        {id_one: 2, id_two: 14, count: 1},
        {id_one: 2, id_two: 15, count: 2},
        {id_one: 3, id_two: 4, count: 3},
        {id_one: 3, id_two: 5, count: 0},
        {id_one: 3, id_two: 6, count: 0},
        {id_one: 3, id_two: 7, count: 0},
        {id_one: 3, id_two: 8, count: 1},
        {id_one: 3, id_two: 9, count: 0},
        {id_one: 3, id_two: 10, count: 1},
        {id_one: 3, id_two: 11, count: 0},
        {id_one: 3, id_two: 12, count: 2},
        {id_one: 3, id_two: 13, count: 1},
        {id_one: 3, id_two: 14, count: 1},
        {id_one: 3, id_two: 15, count: 1},
        {id_one: 4, id_two: 5, count: 0},
        {id_one: 4, id_two: 6, count: 0},
        {id_one: 4, id_two: 7, count: 0},
        {id_one: 4, id_two: 8, count: 0},
        {id_one: 4, id_two: 9, count: 1},
        {id_one: 4, id_two: 10, count: 1},
        {id_one: 4, id_two: 11, count: 1},
        {id_one: 4, id_two: 12, count: 1},
        {id_one: 4, id_two: 13, count: 0},
        {id_one: 4, id_two: 14, count: 1},
        {id_one: 4, id_two: 15, count: 1},
        {id_one: 5, id_two: 6, count: 4},
        {id_one: 5, id_two: 7, count: 1},
        {id_one: 5, id_two: 8, count: 1},
        {id_one: 5, id_two: 9, count: 2},
        {id_one: 5, id_two: 10, count: 0},
        {id_one: 5, id_two: 11, count: 1},
        {id_one: 5, id_two: 12, count: 0},
        {id_one: 5, id_two: 13, count: 0},
        {id_one: 5, id_two: 14, count: 1},
        {id_one: 5, id_two: 15, count: 1},
        {id_one: 6, id_two: 7, count: 1},
        {id_one: 6, id_two: 8, count: 1},
        {id_one: 6, id_two: 9, count: 2},
        {id_one: 6, id_two: 10, count: 0},
        {id_one: 6, id_two: 11, count: 2},
        {id_one: 6, id_two: 12, count: 0},
        {id_one: 6, id_two: 13, count: 0},
        {id_one: 6, id_two: 14, count: 1},
        {id_one: 6, id_two: 15, count: 1},
        {id_one: 7, id_two: 8, count: 1},
        {id_one: 7, id_two: 9, count: 2},
        {id_one: 7, id_two: 10, count: 1},
        {id_one: 7, id_two: 11, count: 0},
        {id_one: 7, id_two: 12, count: 1},
        {id_one: 7, id_two: 13, count: 1},
        {id_one: 7, id_two: 14, count: 3},
        {id_one: 7, id_two: 15, count: 0},
        {id_one: 8, id_two: 9, count: 2},
        {id_one: 8, id_two: 10, count: 2},
        {id_one: 8, id_two: 11, count: 1},
        {id_one: 8, id_two: 12, count: 1},
        {id_one: 8, id_two: 13, count: 2},
        {id_one: 8, id_two: 14, count: 0},
        {id_one: 8, id_two: 15, count: 1},
        {id_one: 9, id_two: 10, count: 1},
        {id_one: 9, id_two: 11, count: 2},
        {id_one: 9, id_two: 12, count: 0},
        {id_one: 9, id_two: 13, count: 0},
        {id_one: 9, id_two: 14, count: 1},
        {id_one: 9, id_two: 15, count: 0},
        {id_one: 10, id_two: 11, count: 1},
        {id_one: 10, id_two: 12, count: 0},
        {id_one: 10, id_two: 13, count: 1},
        {id_one: 10, id_two: 14, count: 1},
        {id_one: 10, id_two: 15, count: 2},
        {id_one: 11, id_two: 12, count: 0},
        {id_one: 11, id_two: 13, count: 1},
        {id_one: 11, id_two: 14, count: 0},
        {id_one: 11, id_two: 15, count: 1},
        {id_one: 12, id_two: 13, count: 3},
        {id_one: 12, id_two: 14, count: 1},
        {id_one: 12, id_two: 15, count: 1},
        {id_one: 13, id_two: 14, count: 1},
        {id_one: 13, id_two: 15, count: 2},
        {id_one: 14, id_two: 15, count: 0}
      ]);
    });
};
